### ISSUE TITLE
Java not supported.

### ISSUE THREAD

**Issue by Terrency** [graalvm/polyglot-embedding-demo#9]
I change language to java, Main can not run.

[java::NFINativeAccess] WARNING: Couldn't find libraries with LLVM bitcode. The default --java.BootLibraryPath will be used.
Exception in thread "main" org.graalvm.polyglot.PolyglotException: java.lang.IllegalStateException: Could not find internal resources for configuration native.
	at org.graalvm.llvm_community/com.oracle.truffle.llvm.runtime.InternalLibraryLocator.create(InternalLibraryLocator.java:89)
	at org.graalvm.llvm.nativemode_community/com.oracle.truffle.llvm.nativemode.NativeConfiguration.<init>(NativeConfiguration.java:66)
	at org.graalvm.llvm.nativemode_community/com.oracle.truffle.llvm.nativemode.NativeConfigurationFactory.createConfiguration(NativeConfigurationFactory.java:102)
	at org.graalvm.llvm.nativemode_community/com.oracle.truffle.llvm.nativemode.NativeConfigurationFactory.createConfiguration(NativeConfigurationFactory.java:47)
	at org.graalvm.llvm_community/com.oracle.truffle.llvm.runtime.config.Configurations.tryCreate(Configurations.java:77)
	at org.graalvm.llvm_community/com.oracle.truffle.llvm.runtime.config.Configurations.createConfiguration(Configurations.java:92)
	at org.graalvm.llvm_community/com.oracle.truffle.llvm.runtime.LLVMLanguage.ensureActiveConfiguration(LLVMLanguage.java:530)
	at org.graalvm.llvm_community/com.oracle.truffle.llvm.runtime.LLVMLanguage.createContext(LLVMLanguage.java:505)
	at org.graalvm.llvm_community/com.oracle.truffle.llvm.runtime.LLVMLanguage.createContext(LLVMLanguage.java:97)
	at org.graalvm.truffle/com.oracle.truffle.api.LanguageAccessor$LanguageImpl.createEnvContext(LanguageAccessor.java:270)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotLanguageContext.ensureCreated(PolyglotLanguageContext.java:652)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotLanguageContext.ensureInitialized(PolyglotLanguageContext.java:731)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.getContextInitialized(PolyglotContextImpl.java:734)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.EngineAccessor$EngineImpl.parseForLanguage(EngineAccessor.java:253)
	at org.graalvm.truffle/com.oracle.truffle.api.TruffleLanguage$Env.parseInternal(TruffleLanguage.java:2557)
	at org.graalvm.llvm.nfi/com.oracle.truffle.llvm.nfi.SulongNFIRootNode$ParseSourceNode.doParse(SulongNFIRootNode.java:56)
	at org.graalvm.llvm.nfi/com.oracle.truffle.llvm.nfi.SulongNFIRootNode$ParseSourceNode.execute(SulongNFIRootNode.java:61)
	at org.graalvm.llvm.nfi/com.oracle.truffle.llvm.nfi.SulongNFIRootNodeGen.execute(SulongNFIRootNodeGen.java:62)
	at <internal/nfi-llvm> null(Unknown)
	at org.graalvm.polyglot/org.graalvm.polyglot.Context.initialize(Context.java:579)
	at embedding/org.example.embedding.Main.main(Main.java:62)
Original Internal Error: 
java.lang.IllegalStateException: Could not find internal resources for configuration native.
	at org.graalvm.llvm_community/com.oracle.truffle.llvm.runtime.InternalLibraryLocator.create(InternalLibraryLocator.java:89)
	at org.graalvm.llvm.nativemode_community/com.oracle.truffle.llvm.nativemode.NativeConfiguration.<init>(NativeConfiguration.java:66)
	at org.graalvm.llvm.nativemode_community/com.oracle.truffle.llvm.nativemode.NativeConfigurationFactory.createConfiguration(NativeConfigurationFactory.java:102)
	at org.graalvm.llvm.nativemode_community/com.oracle.truffle.llvm.nativemode.NativeConfigurationFactory.createConfiguration(NativeConfigurationFactory.java:47)
	at org.graalvm.llvm_community/com.oracle.truffle.llvm.runtime.config.Configurations.tryCreate(Configurations.java:77)
	at org.graalvm.llvm_community/com.oracle.truffle.llvm.runtime.config.Configurations.createConfiguration(Configurations.java:92)
	at org.graalvm.llvm_community/com.oracle.truffle.llvm.runtime.LLVMLanguage.ensureActiveConfiguration(LLVMLanguage.java:530)
	at org.graalvm.llvm_community/com.oracle.truffle.llvm.runtime.LLVMLanguage.createContext(LLVMLanguage.java:505)
	at org.graalvm.llvm_community/com.oracle.truffle.llvm.runtime.LLVMLanguage.createContext(LLVMLanguage.java:97)
	at org.graalvm.truffle/com.oracle.truffle.api.LanguageAccessor$LanguageImpl.createEnvContext(LanguageAccessor.java:270)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotLanguageContext.ensureCreated(PolyglotLanguageContext.java:652)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotLanguageContext.ensureInitialized(PolyglotLanguageContext.java:731)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.getContextInitialized(PolyglotContextImpl.java:734)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.EngineAccessor$EngineImpl.parseForLanguage(EngineAccessor.java:253)
	at org.graalvm.truffle/com.oracle.truffle.api.TruffleLanguage$Env.parseInternal(TruffleLanguage.java:2557)
	at org.graalvm.llvm.nfi/com.oracle.truffle.llvm.nfi.SulongNFIRootNode$ParseSourceNode.doParse(SulongNFIRootNode.java:56)
	at org.graalvm.llvm.nfi/com.oracle.truffle.llvm.nfi.SulongNFIRootNode$ParseSourceNode.execute(SulongNFIRootNode.java:61)
	at org.graalvm.llvm.nfi/com.oracle.truffle.llvm.nfi.SulongNFIRootNodeGen.execute(SulongNFIRootNodeGen.java:62)
	at org.graalvm.truffle/com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:85)
	at org.graalvm.truffle/com.oracle.truffle.api.impl.DefaultDirectCallNode.call(DefaultDirectCallNode.java:59)
	at com.oracle.truffle.truffle_nfi/com.oracle.truffle.nfi.NFIRootNode$LoadLibraryNode.doCached(NFIRootNode.java:115)
	at com.oracle.truffle.truffle_nfi/com.oracle.truffle.nfi.NFIRootNodeFactory$LoadLibraryNodeGen.executeAndSpecialize(NFIRootNodeFactory.java:319)
	at com.oracle.truffle.truffle_nfi/com.oracle.truffle.nfi.NFIRootNodeFactory$LoadLibraryNodeGen.execute(NFIRootNodeFactory.java:280)
	at com.oracle.truffle.truffle_nfi/com.oracle.truffle.nfi.NFIRootNode.execute(NFIRootNode.java:190)
	at org.graalvm.truffle/com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:85)
	at org.graalvm.truffle/com.oracle.truffle.api.impl.DefaultCallTarget.call(DefaultCallTarget.java:102)
	at org.graalvm.espresso/com.oracle.truffle.espresso.ffi.nfi.NFINativeAccess.loadLibraryHelper(NFINativeAccess.java:190)
	at org.graalvm.espresso/com.oracle.truffle.espresso.ffi.nfi.NFISulongNativeAccess.loadLibrary0(NFISulongNativeAccess.java:64)
	at org.graalvm.espresso/com.oracle.truffle.espresso.ffi.nfi.NFINativeAccess.loadLibrary(NFINativeAccess.java:167)
	at org.graalvm.espresso/com.oracle.truffle.espresso.ffi.NativeAccess.loadLibrary(NativeAccess.java:83)
	at org.graalvm.espresso/com.oracle.truffle.espresso.jni.JniEnv.<init>(JniEnv.java:324)
	at org.graalvm.espresso/com.oracle.truffle.espresso.jni.JniEnv.create(JniEnv.java:377)
	at org.graalvm.espresso/com.oracle.truffle.espresso.runtime.EspressoContext.spawnVM(EspressoContext.java:378)
	at org.graalvm.espresso/com.oracle.truffle.espresso.runtime.EspressoContext.initializeContext(EspressoContext.java:319)
	at org.graalvm.espresso/com.oracle.truffle.espresso.EspressoLanguage.initializeContext(EspressoLanguage.java:270)
	at org.graalvm.espresso/com.oracle.truffle.espresso.EspressoLanguage.initializeContext(EspressoLanguage.java:85)
	at org.graalvm.truffle/com.oracle.truffle.api.TruffleLanguage$Env.postInit(TruffleLanguage.java:3772)
	at org.graalvm.truffle/com.oracle.truffle.api.LanguageAccessor$LanguageImpl.postInitEnv(LanguageAccessor.java:288)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotLanguageContext.ensureInitialized(PolyglotLanguageContext.java:771)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.initializeLanguage(PolyglotContextImpl.java:1629)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.initializeLanguage(PolyglotContextImpl.java:1638)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextDispatch.initializeLanguage(PolyglotContextDispatch.java:55)
	at org.graalvm.polyglot/org.graalvm.polyglot.Context.initialize(Context.java:579)
	at embedding/org.example.embedding.Main.main(Main.java:62)
	Suppressed: Attached Guest Language Frames (2)

**Comment by A-D-I-T-Y-A** [comment]
Same issue on my system. Building in IntelliJ on Windows using GraalVM 24.0.1.
